[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckTimeout = 300
startCommand = "bash /app/start.sh"

[deploy.run]
privileged = true
