version: '3.8'

services:
  kafka:
    build:
      context: ./kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 1
    volumes:
      - kafka_data:/data
  kafka-ui:
    build:
      context: ./kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKER: kafka:9092

volumes:
  kafka_data:
